[package]
name = "holiday_gen"
version = "0.1.2"
authors = ["Kim Jin Su <item4_hun@hotmail.com>"]
edition = "2018"

[dependencies]
chrono = "^0.4"
csv = "^1"
serde = "^1.0.80"
serde_derive = "^1.0.80"
serde_json = "^1.0"